spring.data.mongodb.uri=${MONGO_URI:mongodb://localhost:27017/cloudshare}

# CORS Configuration
spring.web.cors.allowed-origins=http://localhost:5173,https://cloud-file-sharing-app.vercel.app
spring.web.cors.allowed-methods=GET,POST,PUT,DELETE,OPTIONS,PATCH
spring.web.cors.allowed-headers=*
spring.web.cors.allow-credentials=true

server.servlet.context-path=/api/v1.0

spring.data.mongodb.auto-index-creation=true

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration

clerk.issuer=${CLERK_ISSUER:https://bold-mollusk-94.clerk.accounts.dev}

clerk.jwks-url=${CLERK_JWKS_URL:https://bold-mollusk-94.clerk.accounts.dev/.well-known/jwks.json}

clerk.webhook.secret=${CLERK_WEBHOOK_SECRET}

#file upload configuration
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=100MB

# Cloudinary Configuration
cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api-key=${CLOUDINARY_API_KEY}
cloudinary.api-secret=${CLOUDINARY_API_SECRET}

# Add another port
server.port=${PORT:8081}
