spring.data.mongodb.uri=${MONGO_URI:mongodb://localhost:27017/cloudshare}

server.servlet.context-path=/api/v1.0

spring.data.mongodb.auto-index-creation=true

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration

clerk.issuer=${CLERK_ISSUER:https://bold-mollusk-94.clerk.accounts.dev}

clerk.jwks-url=${CLERK_JWKS_URL:https://bold-mollusk-94.clerk.accounts.dev/.well-known/jwks.json}

clerk.webhook.secret=${CLERK_WEBHOOK_SECRET}

#file upload configuration
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=100MB

# Add another port
server.port=${PORT:8081}
